-- Dropping Warehouse Schema If Existing Before
DROP SCHEMA IF EXISTS `dw` ;
COMMIT;

-- Creating Warehouse Star Schema
CREATE SCHEMA `dw`;
USE `dw`;

-- Creating Tables
DROP TABLE IF EXISTS `PRODUCTS`;
CREATE TABLE PRODUCTS(
	PRODUCT_ID VARCHAR(6) NOT NULL,
    PRODUCT_NAME VARCHAR(30) NOT NULL,
    PRICE DOUBLE(5,2) DEFAULT 0.0,
    CONSTRAINT `PRODUCTS_PK` PRIMARY KEY (PRODUCT_ID)
);

DROP TABLE IF EXISTS `CUSTOMERS`;
CREATE TABLE CUSTOMERS(
	CUSTOMER_ID VARCHAR(4), 
    CUSTOMER_NAME VARCHAR(30) not null,
    CONSTRAINT `CUSTOMERS_PK` PRIMARY KEY (CUSTOMER_ID)
);

DROP TABLE IF EXISTS `TIMES`;
CREATE TABLE TIMES(
	TIME_ID VARCHAR(8) NOT NULL, 
    TIME_DATE DATE,
	DAY INT,
    MONTH INT,
    YEAR INT,
    CONSTRAINT `TIMES_PK` PRIMARY KEY (TIME_ID)
);

DROP TABLE IF EXISTS `SUPPLIERS`;
CREATE TABLE SUPPLIERS(
	SUPPLIER_ID VARCHAR(5) NOT NULL, 
	SUPPLIER_NAME VARCHAR(30) NOT NULL,
    CONSTRAINT `SUPPLIERS_PK` PRIMARY KEY (SUPPLIER_ID)
);

DROP TABLE IF EXISTS `STORES`;
CREATE TABLE STORES(
	STORE_ID VARCHAR(4) NOT NULL, 
	STORE_NAME VARCHAR(20) NOT NULL, 
    CONSTRAINT `STORES_PK` PRIMARY KEY (STORE_ID)
);

DROP TABLE IF EXISTS `TRANSACTIONS`;
CREATE TABLE TRANSACTIONS(
	TRANSACTION_ID DOUBLE(8,0),
	PRODUCT_ID VARCHAR(6) NOT NULL,
    CUSTOMER_ID VARCHAR(4), 
    TIME_ID VARCHAR(8) NOT NULL, 
    SUPPLIER_ID VARCHAR(5) NOT NULL, 
    STORE_ID VARCHAR(4) NOT NULL,
    QUANTITY DOUBLE(3,0) NOT NULL,
    SALE DOUBLE NOT NULL,
    CONSTRAINT `TRANSACTIONS_PK` PRIMARY KEY(TRANSACTION_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (TIME_ID) REFERENCES TIMES(TIME_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID)
);